import React from 'react';
import Layout from '@theme/Layout';

export default function Home() {
  return (
    <Layout
      title={`My Docusaurus Book`}
      description="A book generated by an AI agent">
      <main>
        <div style={{ padding: '2rem' }}>
          <h1>Welcome to My Book</h1>
          <p>This is the homepage of a book generated by an AI agent.</p>
        </div>
      </main>
    </Layout>
  );
}
